version: "3"

services:
  nodejs:
    # 指定以当前目录下的Dockerfile文件打包成镜像
    build:
      context: .
      dockerfile: Dockerfile
    image: wecom_worktool_backend
    container_name: wecom_worktool_backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      TZ: ${EN_TZ:-Asia/Shanghai}

networks:
  app-network:
    driver: bridge
